[package]
name = "tubuyaita_crypto"
version = "0.1.4"
authors = []
edition = "2021"

[lib]
name = "tubuyaita_crypto"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
hex = "0.4.3"
ed25519-dalek = "1.0.1"

[profile.release]
lto = true
